# .github/workflows/cron.yml
name: Vercel Cron Jobs
on:
  schedule:
    # Test Telegram alle 12:20, 12:30, 12:31
    - cron: '25 14 * * *'  # 12:20 ogni giorno
    - cron: '45 14 * * *'  # 14:30 ogni giorno  
    - cron: '46 14 * * *'  # 12:31 ogni giorno
    
    # Cron jobs originali
    - cron: '0 8 * * *'    # 8:00 ogni giorno
    - cron: '0 12 * * *'   # 12:00 ogni giorno
    - cron: '30 12 * * *'  # 12:30 ogni giorno
    - cron: '0 15 * * *'   # 15:00 ogni giorno
    - cron: '30 15 * * *'  # 15:30 ogni giorno
    - cron: '0 19 * * *'   # 19:00 ogni giorno
    - cron: '30 20 * * *'  # 20:30 ogni giorno
    - cron: '30 23 * * *'  # 23:30 ogni giorno
    - cron: '59 23 * * 0'  # 23:59 ogni domenica

jobs:
  trigger-cron:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Vercel Cron API
        run: |
          curl -X POST ${{ secrets.VERCEL_APP_URL }}/api/cron \
            -H "Content-Type: application/json" \
            --fail-with-body
        continue-on-error: false
        
      - name: Log execution
        run: |
          echo "Cron job triggered at $(date)"
          echo "Target URL: ${{ secrets.VERCEL_APP_URL }}/api/cron"