name: Cron Test
on:
  schedule:
    - cron: '*/5 * * * *'  # Ogni 5 minuti (per test)
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test API
        run: |
          echo "Auto-triggered at $(date)"
          curl -X POST https://vite-react-vagliofabianos-projects.vercel.app/api/cron \
            -H "Content-Type: application/json"